### PR TITLE
fix: Catch network connectivity exceptions

### LINKED ISSUE #197: AndroidNetworkListener and AndroidNetworkConnectivityChecker are crashing on Android 11
## Expected Behavior
SDK shouldn't crash because of ConnectivityManager on Android 11

## Current Behavior
Now we have few crashes on Android 11 devices:

1. First one is connected with the call of `AndroidNetworkListener.setupNetworkCallback`
 ```
 Fatal Exception: java.lang.SecurityException: Package android does not belong to 10438
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
       at android.os.Parcel.createException(Parcel.java:2360)
       at android.os.Parcel.readException(Parcel.java:2343)
       at android.os.Parcel.readException(Parcel.java:2285)
       at android.net.IConnectivityManager$Stub$Proxy.listenForNetwork(IConnectivityManager.java:3609)
       at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3710)
       at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4104)
       at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4074)
       at com.amplitude.android.utilities.AndroidNetworkListener.setupNetworkCallback(AndroidNetworkListener.java:59)
       at com.amplitude.android.utilities.AndroidNetworkListener.startListening(AndroidNetworkListener.java:32)
       at com.amplitude.android.plugins.AndroidNetworkConnectivityCheckerPlugin.setup(AndroidNetworkConnectivityCheckerPlugin.kt:42)
       at com.amplitude.core.platform.Timeline.add(Timeline.kt:23)
       at com.amplitude.core.Amplitude.add(Amplitude.kt:465)
       at com.amplitude.android.Amplitude.buildInternal$suspendImpl(Amplitude.kt:61)
       at com.amplitude.android.Amplitude.buildInternal(Amplitude.kt:1)
       at com.amplitude.core.Amplitude$build$built$1.invokeSuspend(Amplitude.kt:114)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
    
```
2. Second one relates to the call of `AndroidNetworkConnectivityChecker.isConnected`

 ```
 Fatal Exception: java.lang.SecurityException: Package android does not belong to 10511
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2374)
       at android.os.Parcel.createException(Parcel.java:2358)
       at android.os.Parcel.readException(Parcel.java:2341)
       at android.os.Parcel.readException(Parcel.java:2283)
       at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:2456)
       at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1386)
       at com.amplitude.android.utilities.AndroidNetworkConnectivityChecker.isConnected(AndroidNetworkConnectivityChecker.java:42)
       at com.amplitude.android.plugins.AndroidNetworkConnectivityCheckerPlugin$setup$1.invokeSuspend(AndroidNetworkConnectivityCheckerPlugin.kt:25)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
    
```

## Possible Solution
Actually it's a known issue on Android 11: https://issuetracker.google.com/issues/175055271
So the only possible workaround is just adding try-catch block with possible checking build version

## Steps to Reproduce
1. Our cases are 100% background - so maybe it can help for reproducing

## Environment
- Device: Redmi Note 9, Realme C21-Y for example from our crashlytics
- Device OS and Version: only Android 11

### PR DESCRIPTION
**Pull request by izaaz**
### Summary
Fixes #197 and #220 

The network connectivity checker can throw an exception sometimes that causes the app to crash. Wrap them around try catches, suppress exceptions and default to online in case of an error

### Checklist

* [ ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Kotlin/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:

### CODE REVIEW

File: android/src/main/java/com/amplitude/android/utilities/ExceptionUtils.kt [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package com.amplitude.android.utilities
+
+import com.amplitude.common.Logger
+
+object ExceptionUtils {
```
Comment (crleona) [inline android/src/main/java/com/amplitude/android/utilities/ExceptionUtils.kt:5]: IMO, I would not pull this out into a utility class, at least without further usage. We generally want to handle all exceptions, this encourages ignoring them.

File: android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt [hunk 2]
```diff
@@ -35,23 +35,28 @@ class AndroidNetworkConnectivityChecker(private val context: Context, private va
...
 
-        val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE)
-        if (cm is ConnectivityManager) {
-            if (isMarshmallowAndAbove) {
-                val network = cm.activeNetwork ?: return false
-                val capabilities = cm.getNetworkCapabilities(network) ?: return false
-
-                return capabilities.hasTransport(NetworkCapabilities.TRANSPORT_WIFI) ||
-                    capabilities.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)
+        val result = ExceptionUtils.safeInvoke(logger) {
```
Comment (crleona) [inline android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt:38]: Could you please leave a comment pointing to the Android issue that this fixes? (Here and anywhere else that we're working around the same bug).

**Review by crleona — APPROVED** [review]

File: android/src/main/java/com/amplitude/android/utilities/AndroidNetworkListener.kt
Comment (Mercy811) [inline android/src/main/java/com/amplitude/android/utilities/AndroidNetworkListener.kt:1]: Shall we also try and catch [registerNetworkCallback](https://github.com/amplitude/Amplitude-Kotlin/blob/6a8491006c94d4f617cb392e3e82afa32330e451/android/src/main/java/com/amplitude/android/utilities/AndroidNetworkListener.kt#L59)? It appears in both issues' stack traces and is mentioned at https://issuetracker.google.com/issues/175055271 that it can sometimes throw an exception.

File: android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt (hunk 2 above)
Comment (Mercy811) [reply android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt:38]: @crleona why do we want a comment in code if source control already maintains the history?

**Review by Mercy811 — COMMENTED** [review]
Thanks Izaaz for fixing this. As it's a known issue and 99% of devices affected are Pixel devices (2/3) running android 11 according to https://issuetracker.google.com/issues/175055271. Wrapping where exceptions are thrown makes sense to me.

File: android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt (hunk 2 above)
Comment (crleona) [reply android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt:38]: We didn't catch this the first time, so it's non-obvious. Why should I round trip through version control versus having that information right in front of me in the source code?

File: android/src/main/java/com/amplitude/android/utilities/ExceptionUtils.kt (hunk 1 above)
Comment (izaaz) [reply android/src/main/java/com/amplitude/android/utilities/ExceptionUtils.kt:5]: Sounds good. That makes sense. I've removed this class

File: android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt (hunk 2 above)
Comment (izaaz) [reply android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt]: Comments are cheap and no harm adding the links directly to save the extra round trip. Added more comments.
