### PR TITLE
fix: correctly format client_upload_time in HTTP request when minIdLength is set

### LINKED ISSUE #159: Malformed Event(s) JSON using 1.12.0 SDK
## Expected Behavior
Generated events JSON should be valid

## Current Behavior
Generated events JSON is invalid. The value of field `client_upload_time` should be a string

```
{
"api_key": "API_KEY",
"client_upload_time": 2023-11-13T12
07: 48.509Z,
"events": [
{
....
}]

```

## Possible Solution
In file `core/src/main/java/com/amplitude/core/utilities/HttpClient.kt#getBodyStr` the else statement (when `minId != null` doesn't add `""` around the field)

## Steps to Reproduce
Log an event to amplitude

## Environment
- Device: Android Emulator sdk_gphone64_arm64
- Device OS and Version: Android OS 13

### PR DESCRIPTION
**Pull request by justin-fiedler**
### Summary

* Fixes #159, [AMP-88899](https://amplitude.atlassian.net/browse/AMP-88899)
* Correctly handles `client_upload_time` when `minIdLength` is set in the configuration
* Added tests for HttpClient

### Checklist

* [x] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Kotlin/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?: No

[AMP-88899]: https://amplitude.atlassian.net/browse/AMP-88899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+            serverUrl = server.url("/").toString()
+        )
+        val event = BaseEvent()
+        event.eventType = "test"
+
+        val httpClient = spyk(HttpClient(config))
+        every { httpClient.getCurrentTimeMillis() } returns clientUploadTimeMillis
+
+        val connection = httpClient.upload()
+        System.currentTimeMillis()
```
Comment (Mercy811) [inline core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt:53]: It seems that this is not used? And the same for the other test.

**Review by Mercy811 — APPROVED** [review]
Thank you Justin for fixing the payload and adding tests.

File: core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt (hunk 1 above)
Comment (justin-fiedler) [reply core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt]: Good catch. Thanks
